# HTTP客户端设置
http.client:
  #最大连接数
  maxTotal: 40
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 500

# Gogo配置
gogo:
  # 监听端口
  port: 4999
  # 日间模式开始时间
  day-mode-start-time-string: "07:00"
  # 日间模式结束时间
  day-mode-end-time-string: "19:00"
  # 首页标语
  slogan: 欢迎<a href="https://github.com/zenuo/gogo">star</a>，蟹蟹支持🥳
  # 搜索结果替换规则
  substitute:
    - https://zh.wikipedia.org#https://176.122.157.73:3457